server:
  port: 8082

spring:
  application:
    name: payments
  datasource:
    url: jdbc:sqlite:payments.db
    driver-class-name: org.sqlite.JDBC
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none

app:
  events:
    url: http://localhost:8083
  payment:
    fail-mode: never
    fail-threshold: 1000.0
